server:
  port: 8080
spring:
  application:
    name: emp-mgr-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/emp-mgr-db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
