version: '3.8'

services:

  postgres-warehouse:
    container_name: emp-mgr-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emp-mgr-db
    ports:
      - "5432:5432"